### ISSUE TITLE
404 when accessing Clone https://gitlab.com/UniGrammar.py/grammars

### ISSUE THREAD

**Issue by CuchulainX** [UniGrammar/UniGrammar.py#1]
Hi,

I receive a 404 from the above gitlab page. mentioned in the repo readme

/C

**Comment by KOLANICH** [comment]
Thank you for your interest to UniGrammar. I have migrated back to GitHub since GitLab inc. behaves in unethical way (JS promotion, recaptcha) and incorporated its way into GitLab, both into the proprietary edition used on gitlab.com (the thing that has made me the most angry was Cloudflare "under attack" browser fingerprinting script) and into free editions used by various projects. So all the repos currently live on GitHub. Including the grammars repo: https://github.com/UniGrammar/grammars

In fact the only grammar currently implemented is https://github.com/UniGrammar/grammars/blob/master/configs/apt_source/grammar.yug . The rest are to be implemented/translated from ANTLR4. I have decided that the manual translation is inefficient, so I decided to write an automatic one. Unfortunately currently I don't have a lot of time to spend on this project, so collaboration is always welcome. The main issue currently is #2 - the lack of module system, which makes it hard to develop and debug complex grammars.

I have fixed the ReadMe.
